
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb://localhost:27017/test
      JWT_SECRET: test-secret-key-for-ci-only
      PORT: 5050

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['6.0']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package.json'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies (server)
        run: npm install

      - name: Install dependencies (client)
        run: cd client && npm install

      - name: Create config.env
        run: |
          echo "MONGODB_URI=${{ env.MONGODB_URI }}" > config.env
          echo "JWT_SECRET=${{ env.JWT_SECRET }}" >> config.env
          echo "PORT=${{ env.PORT }}" >> config.env

      - name: Lint
        run: |
          npm run lint --if-present
          cd client && npm run lint --if-present

      - name: Build
        run: |
          cd client && npm run build

      - name: Test
        run: |
          npm test --if-present
          cd client && npm test --if-present